### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by moria-msn** [nobutnk/redpen-maven-plugin#1]
ライセンスの明確な記載がありませんが、どのようになっているのでしょうか。
改変・再配布等をしたいため、記載いただけますと助かります。

**Comment by nobutnk** [comment]
すみませんでした。対応します。少々お待ちください

**Comment by nobutnk** [comment]
対応しました

**Comment by moria-msn** [comment]
ご対応ありがとうございます。
